export default {
    UPDATE_FIELD_STATE: "UPDATE_FIELD_STATE",
    UPDATE_FIELD_MINES: "UPDATE_FIELD_MINES",
    GENERATE_FIELD_MINES: "GENERATE_FIELD_MINES",
    INCREMENT_TIME: "INCREMENT_TIME",
    RESET_TIME: "RESET_TIME",
    INCREMENT_MINES: "INCREMENT_MINES",
    DECREMENT_MINES: "DECREMENT_MINES",
    RESTART_GAME: "RESTART_GAME"
}